[package]
name = "solana_transfer_bot"
version = "0.1.0"
edition = "2021"
authors = ["Solana Developer"]
description = "솔라나 토큰 전송 봇"

[dependencies]
solana-client = "1.17.0"
solana-sdk = "1.17.0"
bs58 = "0.5.0"
dotenv = "0.15.0"
url = "2.4.1" 